# -*- coding: utf-8 -*-
"""Nandana_Price_Groq_Chat_bot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19M9l3Y-aTOD0Klm323JED6edgV56G5Fb

#Install Packages
"""

pip install groq

pip install gradio

"""# Import the Packages"""

import gradio
from groq import Groq

client = Groq(
    api_key="GROQ_API_KEY",
)

"""#Define a function to give content and role"""

def initialize_messages():
    return [{"role": "system",
             "content": "I want to build a chatbot that provides today's prices of daily essential items in Indian Rupees—a price checker and assistance chatbot for real-time cost updates. No introduction about the chatbot, only give the items and their prices."}]

"""#Assign it to a variable"""

messages_prmt = initialize_messages()

print(type(messages_prmt))

[{},{}]

"""#Define a function to connect with LLM"""

def customLLMBot(user_input, history):
    global messages_prmt

    messages_prmt.append({"role": "user", "content": user_input})

    response = client.chat.completions.create(
        messages=messages_prmt,
        model="llama3-8b-8192",
    )
    print(response)
    LLM_reply = response.choices[0].message.content
    messages_prmt.append({"role": "assistant", "content": LLM_reply})

    return LLM_reply

"""#Create an object of chat interface class in gradio"""

iface = gradio.ChatInterface(customLLMBot,
                     chatbot=gradio.Chatbot(height=300),
                     textbox=gradio.Textbox(placeholder="Ask me about the current price of any daily essential item in Indian Rupees."),
                     title="Price Assistant ChatBot",
                     description="Chatbot for Daily Price Assistance in Indian Rupees",
                     theme="soft",
                     examples=["Hi!","What is today’s price of rice?","How much is 1 kg of tomatoes today?","Check the price of milk in INR.","What's the cost of onions today?","Give me today's vegetable prices.","Show me the price list for daily essentials.","Is sugar price up or down today?","Tell me today's grocery prices.","What's the market rate of atta (wheat flour) today?"],
                     submit_btn=True
                     )

"""#Call launch function to execute"""

iface.launch(share=True)

code = """<PASTE YOUR FULL CODE HERE>"""
with open('price_assistant_chatbot.py', 'w') as f:
    f.write(code)

